helpdesk/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

app_name = "helpdesk"
urlpatterns = [
    path('login', views.login_view, name='login_view'),
    path('logging_in', views.logging_in, name='logging_in'),
    path('list-tickets.html', views.ListTickets.as_view(), name='list-tickets'),
    path('new_ticket.html', views.new_ticket, name='new_ticket'),
    path('send_ticket', views.send_ticket, name='send_ticket'),
    path('faq.html', views.faq, name='faq'),
    path('view-ticket_<int:ticket_num>', views.view_ticket, name='view_ticket'),
    path('finish_ticket_<int:ticket_num>', views.finish_ticket, name='finish_ticket'),
    path('list-messages.html', views.list_messages, name='list_messages'),
    path('view_message_<int:message_num>', views.view_message, name='view_message'),
    path('new-message.html', views.new_message, name='new_message'),
    path('send_message', views.send_message, name='send_message'),
    path('list-tickets-admin.html', views.ListTicketsAdmin.as_view(), name='list_tickets_admin'),
    path('list-completed-tickets-admin.html', views.ListCompletedTicketsAdmin.as_view(),
         name='list-completed-tickets'),
    path('view-ticket_admin_<int:ticket_num>', views.view_ticket_admin, name='view_ticket_admin'),
    path('accept_ticket_<int:ticket_num>', views.accept_ticket, name='accept_ticket'),
    path('send_ticket_message', views.send_ticket_message, name='send_ticket_message'),
    path('logout', views.logout_view, name='logout')
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('helpdesk/', include('helpdesk.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

helpdesk/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.db.models.functions import ExtractDay, ExtractMonth, ExtractYear


class Department(models.Model):
    name = models.CharField(max_length=100)
    head = models.ForeignKey('auth.User', null=True, on_delete=models.CASCADE, related_name="head")

    def __str__(self):
        return self.name + " " + str(self.id)


class Ticket(models.Model):
    requestor = models.ForeignKey('auth.User', on_delete=models.CASCADE, related_name="requestor")
    worker = models.ForeignKey('auth.User', on_delete=models.SET_NULL, null=True, related_name="worker")
    theme = models.CharField(max_length=100, default="")
    targeted_department = models.ForeignKey('Department', on_delete=models.CASCADE, related_name="targeted_department")
    place = models.CharField(max_length=100, default="")
    priority = models.IntegerField(default="0")  # 0-Низкий 1-Средний 2-Высокий
    details = models.CharField(max_length=1000, default="")
    pub_date = models.DateTimeField('date published')
    exp_date = models.DateTimeField('expiration date')
    finished = models.BooleanField(default="False")
    deleted = models.BooleanField(default="False")
    chat = models.TextField(default="")

    def __str__(self):
        return self.theme + " " + str(self.id)

    def nice_exp_date(this):
        return ExtractDay(this.exp_date) + "/" + ExtractMonth(this.exp_date) + "/" + ExtractYear(this.exp_date)


class EmployeesInDepartments(models.Model):
    person = models.ForeignKey('auth.User', on_delete=models.CASCADE, related_name="person")
    department = models.ForeignKey('Department', on_delete=models.CASCADE, related_name="department")

    def __str__(self):
        return self.person.first_name + self.person.last_name + " X " + self.department.name + " " + str(self.id)


class QuestionsAndAnswers(models.Model):
    question = models.CharField(max_length=1000, default="")
    answer = models.CharField(max_length=1000, default="")

    def __str__(self):
        return self.question + " " + str(self.id)


class Message(models.Model):
    sender = models.ForeignKey('auth.User', on_delete=models.CASCADE, related_name="sender")
    reciver = models.ForeignKey('auth.User', on_delete=models.CASCADE, related_name="reciver")
    text = models.CharField(max_length=1000, default="")
    ticket = models.ForeignKey('Ticket', on_delete=models.CASCADE)
    deleted = models.BooleanField(default="False")
    status = models.CharField(max_length=20, default="Отправлено")
    date = models.DateTimeField('date')

# buh 1w2e3r4t
# tech 1w2e3r4t
# buhxtech 1w2e3r4t
# noone 1w2e3r4t

helpdesk/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone
from django.db.models import Q
from datetime import datetime
from . import models


# Create your views here.
def login_view(request):
    """Login into helpdesk page."""
    if request.user.is_authenticated:
        return redirect(reverse('helpdesk:list-tickets'))
    context = {}
    try:
        if request.GET['type'] == 'wrong_pass':
            context['wrong_pass'] = True
    except:
        pass
    return render(request, "helpdesk/index.html", context)


def logging_in(request):
    """Login in process."""
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return redirect(reverse('helpdesk:list-tickets'))
    else:
        # Return an 'invalid login' error message.
        return redirect(reverse('helpdesk:login_view') + "?&type=wrong_pass")


class AbstractTicketListing(LoginRequiredMixin, generic.ListView):
    template_name = 'helpdesk/list-tickets.html'
    login_url = 'helpdesk:login_view'
    redirect_field_name = 'redirect_to'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user.first_name + " " + self.request.user.last_name
        if models.EmployeesInDepartments.objects.filter(person=self.request.user).count() > 0:
            context['isWorker'] = True
        return context


class ListTickets(AbstractTicketListing):
    """Get all tickets of the person."""

    def get_queryset(self):
        result_list = models.Ticket.objects.filter(requestor=self.request.user)
        return result_list.filter(finished=False, deleted=False).order_by('id')


class ListCompletedTickets(AbstractTicketListing):
    """List all completed tickets of the requesting user."""
    def get_queryset(self):
        result_list = models.Ticket.objects.filter(requestor=self.request.user)
        return result_list.filter(finished=False, deleted=False).order_by('id')


@login_required
def new_ticket(request):
    """New ticket creation page."""
    context = {"user": request.user.first_name + " " + request.user.last_name,
               "departments": models.Department.objects.all()}
    if models.EmployeesInDepartments.objects.filter(person=request.user).count() > 0:
        context['isWorker'] = True
    return render(request, "helpdesk/new-ticket.html", context)


@login_required
def send_ticket(request):
    """Sending ticket page."""
    exp_date = request.POST['date']
    translated_date = exp_date[6:10] + "-" + exp_date[0:2] + "-" + exp_date[3:5]
    if datetime.strptime(translated_date, '%Y-%m-%d') < timezone.now().replace(tzinfo=None):
        return redirect('helpdesk:new_ticket')
    models.Ticket.objects.create(requestor=request.user,
                                 theme=request.POST['theme'],
                                 targeted_department=models.Department.objects.get(pk=request.POST['division']),
                                 place=request.POST['room'],
                                 exp_date=translated_date,
                                 details=request.POST['message'],
                                 pub_date=timezone.now()
                                 )
    return redirect('helpdesk:list-tickets')


def get_user_num(lista, request):
    def name_checker(message, name):
        if (message.find(name) == 0):
            return 0
        return 1

    return list(
        map(lambda item: (item, name_checker(item, request.user.first_name + " " + request.user.last_name)), lista))


@login_required
def view_ticket(request, ticket_num):
    """View ticket as ticket creator."""
    context = {"obj": get_object_or_404(models.Ticket, pk=ticket_num, deleted=False, finished=False),
               "user": request.user.first_name + " " + request.user.last_name}
    if models.EmployeesInDepartments.objects.filter(person=request.user).count() > 0:
        context['isWorker'] = True
    result_list = models.Ticket.objects.filter(requestor=request.user).order_by('-id')
    context["tickets"] = result_list.filter(finished=False, deleted=False)
    context["chat"] = get_user_num(context["obj"].chat.split("\n"), request)
    try:
        context["chat"].pop(0)
    except ValueError:
        context["chat"] = context["obj"].chat.split("\n")
    if context["obj"].requestor == request.user:
        return render(request, "helpdesk/view-ticket.html", context)
    else:
        return redirect(reverse('helpdesk:list-tickets'))


@login_required
def finish_ticket(request, ticket_num):
    """Accept ticket as ticket creator."""
    obj = models.Ticket.objects.get(pk=ticket_num)
    if request.POST["result"] == 'Засчитать':
        obj.finished = True
    if request.POST["result"] == 'Удалить':
        print(request.POST["result"])
        obj.deleted = True
    obj.save()
    return redirect('helpdesk:list-tickets')


@login_required
def faq(request):
    """Show faq."""
    context = {"questions": models.QuestionsAndAnswers.objects.all(),
               "user": request.user.first_name + " " + request.user.last_name}
    if models.EmployeesInDepartments.objects.filter(person=request.user).count() > 0:
        context['isWorker'] = True
    return render(request, "helpdesk/faq.html", context)

class AbstractAdminTicketListing(AbstractTicketListing):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['isAdmining'] = True
        return context

class ListTicketsAdmin(AbstractAdminTicketListing):
    """List tickets to the worker's department."""
    def get_queryset(self):
        departments_querySet = models.EmployeesInDepartments.objects.filter(person=self.request.user)
        department_list = []
        for department in departments_querySet.all():
            department_list.append(department.department.pk)

        result_list = models.Ticket.objects.filter(targeted_department__pk__in=department_list, finished=False,
                                                   deleted=False)
        return result_list.order_by('-pub_date')

class ListCompletedTicketsAdmin(AbstractAdminTicketListing):
    """List completed tickets in worker's department."""
    def get_queryset(self):
        departments_querySet = models.EmployeesInDepartments.objects.filter(person=self.request.user)
        department_list = []
        for department in departments_querySet.all():
            department_list.append(department.department.pk)

        result_list = models.Ticket.objects.filter(targeted_department__pk__in=department_list, finished=True,
                                                   deleted=False)
        return result_list.order_by('-pub_date')


@login_required
def send_ticket_message(request):
    """Send message to ticket chat."""
    ticket = models.Ticket.objects.get(pk=request.POST["ticket_num"])
    message = request.POST["chat-message"].replace("\n", " ")
    ticket.chat += "\n" + request.user.first_name + " " + request.user.last_name + ":" + message
    ticket.save()
    if request.POST["user_type"] == "user":
        return redirect('helpdesk:view_ticket', ticket_num=ticket.pk)
    else:
        return redirect('helpdesk:view_ticket_admin', ticket_num=ticket.pk)


@login_required
def view_ticket_admin(request, ticket_num):
    """View ticket as a worker."""
    context = {"obj": get_object_or_404(models.Ticket, pk=ticket_num, deleted=False),
               "user": request.user.first_name + " " + request.user.last_name}
    get_object_or_404(models.EmployeesInDepartments,
                      person=request.user,
                      department=context["obj"].targeted_department)
    departments_querySet = models.EmployeesInDepartments.objects.filter(person=request.user)
    context["chat"] = get_user_num(context["obj"].chat.split("\n"), request)
    try:
        context["chat"].pop(0)
    except ValueError:
        context["chat"] = context["obj"].chat.split("\n")
    department_list = []
    for department in departments_querySet.all():
        department_list.append(department.department.pk)
    result_list = models.Ticket.objects.filter(targeted_department__pk__in=department_list, finished=False,
                                               deleted=False)
    result_list.order_by('-pub_date')
    context["tickets"] = result_list
    if models.EmployeesInDepartments.objects.filter(person=request.user).count() > 0:
        context['isWorker'] = True
    return render(request, 'helpdesk/view-ticket_admin.html', context)


@login_required
def accept_ticket(request, ticket_num):
    """Accept ticket as a worker."""
    ticket = get_object_or_404(models.Ticket, pk=ticket_num, deleted=False, finished=False, worker=None)
    if models.EmployeesInDepartments.objects.filter(person=request.user,
                                                    department=ticket.targeted_department).count() > 0:
        ticket.worker = request.user
        ticket.save()
    return redirect('helpdesk:list_tickets_admin')


def logout_view(request):
    """Logout."""
    logout(request)
    return redirect('helpdesk:login_view')


# Message system is deprecated, so no docstrings.

@login_required
def list_messages(request):
    context = {"user": request.user.first_name + " " + request.user.last_name,
               }
    messages_array = models.Message.objects.filter(Q(sender=request.user) | Q(reciver=request.user)).order_by('-date')
    context["messages"] = messages_array
    context["watcher"] = request.user

helpdesk/templates/helpdesk/father_frame.html
<!DOCTYPE html>
{%load static%}
<html lang="ru">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Help Desk v 1.0 | Новое сообщения</title>
	<meta name="description" content="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolorempor incididunt set">
	<meta name="keywords" content="lorem, ipsum, dolor, sit, amet, consectetur, adipisicing, elit">
	<!-- jQuery & Bootstrap JS -->
	<script src="{%static 'js/jquery-3.3.1.min.js'%}"></script>
	<script src="{%static 'js/bootstrap.min.js'%}"></script>
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="{%static 'css/bootstrap-reboot.min.css'%}">
	<link rel="stylesheet" href="{%static 'css/bootstrap.min.css'%}">	
	<!-- CSS Styles -->
	<link rel="stylesheet" href="{%static 'css/main.css'%}">
	<link rel="stylesheet" href="{%static 'css/media-queries.css'%}">

</head>
<body>
	<header class="header" id="header">
		<div class="container">
			<div class="row d-flex align-items-center justify-content-between">
				<div class="col-lg-2">
					<div class="logo ttu text-center text-lg-left">
					</div>
				</div>
				<div class="col-lg-4 d-flex justify-content-center justify-content-lg-end">
					<nav>
						<ul class="menu ttu d-flex">
							{%if isWorker%}
							<li class="menu__item">
								<a href="{%url 'helpdesk:list_tickets_admin'%}" class="menu__link">
									Рассмотреть заявки
								</a>
							</li>
							<li class="menu__item">
								<a href="{%url 'helpdesk:list-completed-tickets'%}" class="menu__link">
									Завершенные заявки
								</a>
							</li>
							{%endif%}
							<li class="menu__item">
								<a href="{%url 'helpdesk:list-tickets'%}" class="menu__link">
									Заявки
								</a>
							</li>
							<li class="menu__item">
								<a href="{%url 'helpdesk:faq'%}" class="menu__link">
									F.A.Q.
								</a>
							</li>
						</ul>
					</nav>
				</div>
				<div class="col-lg d-flex align-items-center justify-content-center justify-content-lg-end">
					<img src="{%static 'img/icon-user.png'%}" class="user-logo">
					<div class="user-account">
						<p class="user-name">
							{{user}}
						</p>
					</div>
					<a href="{%url 'helpdesk:logout'%}"><div class="exit"></div></a>
				</div>
			</div>
		</div>
	</header>
	{%block contents%}{%endblock%}
	<footer class="footer" id="footer">
		<div class="container"></div>
	</footer>
	<!-- JS Scripts -->
	<script src="{%static 'js/main.js'%}"></script>
</body>
</html>

helpdesk/templates/helpdesk/index.html
<!DOCTYPE html>
{%load static%}
<html lang="ru">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Help Desk v 1.0 | Новое сообщения</title>
	<meta name="description" content="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolorempor incididunt set">
	<meta name="keywords" content="lorem, ipsum, dolor, sit, amet, consectetur, adipisicing, elit">
	<!-- jQuery & Bootstrap JS -->
	<script src="{%static 'js/jquery-3.3.1.min.js'%}"></script>
	<script src="{%static 'js/bootstrap.min.js'%}"></script>
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="{%static 'css/bootstrap-reboot.min.css'%}">
	<link rel="stylesheet" href="{%static 'css/bootstrap.min.css'%}">	
	<!-- CSS Styles -->
	<link rel="stylesheet" href="{%static 'css/main.css'%}">
	<link rel="stylesheet" href="{%static 'css/media-queries.css'%}">

</head>
<body>
	<header class="header" id="header">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="form-enter-wr">
						<form action="{%url 'helpdesk:logging_in'%}" method="POST">
							{% csrf_token %}
							<div class="enter">
								<img src="{% static 'img/icon-user.png'%}" alt="icon User" class="icon-user">
								<input name="username" type="text" class="input-login" placeholder="Логин">
								<input name="password" type="password" class="input-password" placeholder="Пароль">
								<input value="Войти" type="submit" class="btn btn-enter">
								{%if wrong_pass == True%}
								Неверное имя пользователя или пароль
								{%endif%}
								<!--
								<a href="#" class="forgot-password" target="_blank">Забыли пароль?</a>
								-->
							</div>
						</form>
						<!--
						<div class="new-worker">
							<p class="new-worker__title">
								Вы новый сотрудник?
							</p>
							<input type="text" class="input-id" placeholder="Введите ваш ID">
							<button type="button" class="btn btn-send-query">Отправить запрос</button>
						</div>
						-->
					</div>
				</div>
			</div>
		</div>
	</header>
	<!-- JS Scripts -->
	<script src="{%static 'js/main.js'%}"></script>
</body>
</html>

helpdesk/templates/helpdesk/list-messages.html
{%extends 'helpdesk/father_frame.html'%}
{%block contents%}
	<section class="section-one-class" id="section-one-id">
		<div class="container">
			<div class="row">
				<div class="col">
					<a href="#" onclick="history.back();return false;" class="toback">Назад</a>
				</div>
			</div>
			<div class="row">
				<div class="col-lg d-flex justify-content-center">
					<ul class="list-messages">
						<li class="wr-label d-flex justify-content-between">
							<div class="label-text">
								<p>Тема сообщения(проблема)</p>
							</div>
							<div class="label-depart">
								<p>Отдел</p>
							</div>
							<div class="label-status">
								<p>Лицо</p>
							</div>
							<div class="label-date">
								<p>Дата</p>
							</div>
						</li>
						{%for message in messages%}
							<li class="wr-messages">
								<a href="{%url 'helpdesk:view_message' message.pk%}" class="d-flex justify-content-between">
									<div class="message-text">
										<p>{{message.ticket.theme}}</p>
									</div>
									<div class="message-depart">
										<p>{{message.ticket.targeted_department.name}}</p>
									</div>
									<div class="message-status">
										<p>
											{%if message.sender is watcher%}{{message.sender.first_name}} {{message.sender.last_name}}{%else%}{{message.reciver.first_name}} {{message.reciver.last_name}}{%endif%}
										</p>
									</div>
									<div class="message-date">
										<p>{{message.date}}</p>
									</div>
								</a>
							</li>
						{%endfor%}
					</ul>
				</div>
			</div>
			<div class="row">
				<div class="col">
					<a href="{%url 'helpdesk:new_message'%}" class="btn btn_new-message">
						+ Новое сообщение
					</a>
				</div>
			</div>
		</div>
	</section>
{%endblock%}

helpdesk/templates/helpdesk/view-ticket.html
{%extends 'helpdesk/father_frame.html'%}
{%block contents%}
	<section class="section-two-class" id="section-two-id">
		<div class="container">
			<div class="row">
				<div class="col">
					<a href="#" onclick="history.back();return false;" class="toback">Назад</a>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-4 d-flex justify-content-center">
					<ul class="list-tickets">
						<li class="wr-label d-flex justify-content-between">
							<div class="label-name_ticket label-name_ticket-view">
								<p># заявки</p>
							</div>
							<div class="label-text_ticket label-text_ticket-view">
								<p>Тема</p>
							</div>
						</li>
						{%for ticket in tickets%}
							<li class="wr-tickets">
							<a href="{%url 'helpdesk:view_ticket' ticket.pk%}" class="d-flex justify-content-between">
									<div class="ticket-name ticket-name_view">
										<p>{{ticket.pk}}</p>
									</div>
									<div class="ticket-text ticket-text_view">
										<p>{{ticket.theme}}</p>
									</div>
								</a>
							</li>
						{%endfor%}
					</ul>
				</div>
				<div class="col-lg-8 d-flex justify-content-end">
					<form  method="POST" action="{%url 'helpdesk:finish_ticket' obj.pk%}" class="log clients__form review-form" id="popupMessage">
						{% csrf_token %}
						<h3 class="log__title">Заявка</h3>
						<div class="log__wrap">
							<div class="log__group">
								<label>Приступил к выполнению:</label>
								<p class="log__input">
									{%if obj.worker.first_name == NULL%}Ожидается{%else%}{{obj.worker.first_name}} {{obj.worker.last_name}}{%endif%}
								</p>
							</div>
							<div class="log__group">
								<label>Тема (проблема):</label>
								<p class="log__input">
									{{obj.theme}}
								</p>
							</div>
							<div class="log__inner-wrap">
								<div class="log__group">
									<label>Отдел:</label>
									<p class="log__input">
										{{obj.targeted_department.name}}
									</p>
								</div>
								<div class="log__group">
									<label>Место (кабинет):</label>
									<p class="log__input">
										{{obj.place}}
									</p>
								</div>
								<div class="log__group log__group_socials">
									<label>До:</label>
									<p class="log__input">
										{%if obj.priority == 0%}{%endif%}{%if obj.priority == 2%}{%endif%}{%if obj.priority == 1%}{%endif%}
										{{obj.exp_date.day}}/{{obj.exp_date.month}}/{{obj.exp_date.year}}
									</p>
								</div>
							</div>
							<div class="log__group log__group_textarea">
								<label>Описание проблемы:</label>
								<p class="log__input">
									{{obj.details}}
								</p>
							</div>
						</div>
						{%if obj.worker.first_name == NULL%}
							<input id="reject" name="result" type="submit" data-submit value="Удалить" class="btn btn_del"/>
						{%else%}
							<input id="agree" name="result" type="submit" data-submit value="Засчитать" class="btn btn_agree"/>
						{%endif%}
					</form>
				</div>
			</div>--
			<div class="row">
				<div class="col-lg">
					<div class="chat-window">
						{%for chat_message,who_sent in chat%}
						<div class="user_{%if who_sent == 0%}self{%endif%}{%if who_sent == 1%}different{%endif%}">{{chat_message}}</div>
						<br>
						{%endfor%}
					</div>
					<form action="{%url 'helpdesk:send_ticket_message'%}" method="POST" class="form-chat d-flex">
						{% csrf_token %}
						<textarea name="chat-message" placeholder="Введите текст" required></textarea>
						<input type="hidden" name="ticket_num" value="{{obj.pk}}">
						<input type="hidden" name="user_type" value="user">
						<button type="submit" class="chat-send"></button>
					</form>
				</div>
			</div>
		</div>
	</section>	
{%endblock%}

helpdesk/templates/helpdesk/view-ticket_admin.html
{%extends 'helpdesk/father_frame.html'%}
{%block contents%}
	<section class="section-two-class" id="section-two-id">
		<div class="container">
			<div class="row">
				<div class="col">
					<a href="#" onclick="history.back();return false;" class="toback">Назад</a>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-4 d-flex justify-content-center">
					<ul class="list-tickets">
						<li class="wr-label d-flex justify-content-between">
							<div class="label-name_ticket label-name_ticket-view">
								<p># заявки</p>
							</div>
							<div class="label-text_ticket label-text_ticket-view">
								<p>Тема</p>
							</div>
						</li>
						{%for ticket in tickets%}
							<li class="wr-tickets">
							<a href="{%url 'helpdesk:view_ticket_admin' ticket.pk%}" class="d-flex justify-content-between">
									<div class="ticket-name ticket-name_view">
										<p>{{ticket.pk}}</p>
									</div>
									<div class="ticket-text ticket-text_view">
										<p>{{ticket.theme}}</p>
									</div>
								</a>
							</li>
						{%endfor%}
					</ul>
				</div>
				<div class="col-lg-8 d-flex justify-content-end">
					<form action="{%url 'helpdesk:accept_ticket' obj.pk%}" class="log clients__form review-form" id="popupMessage">
						<h3 class="log__title">Заявка </h3>
						<div class="log__wrap">
							<div class="log__group">
								<label>От пользователя:</label>
								<p class="log__input">
									{{obj.requestor.first_name}} {{obj.requestor.last_name}}
								</p>
							</div>
							<div class="log__group">
								<label>Тема (проблема):</label>
								<p class="log__input">
									{{obj.theme}}
								</p>
							</div>
							<div class="log__inner-wrap">
								<div class="log__group">
									<label>Отдел:</label>
									<p class="log__input">
										{{obj.targeted_department.name}}
									</p>
								</div>
								<div class="log__group">
									<label>Место (кабинет):</label>
									<p class="log__input">
										{{obj.place}}
									</p>
								</div>
								<div class="log__group log__group_socials">
									<label>До:</label>
									<p class="log__input">
										{%if obj.priority == 0%}{%endif%}{%if obj.priority == 2%}{%endif%}{%if obj.priority == 1%}{%endif%}
										{{obj.exp_date.day}}/{{obj.exp_date.month}}/{{obj.exp_date.year}}
									</p>
								</div>
							</div>
							<div class="log__group log__group_textarea">
								<label>Описание проблемы:</label>
								<p class="log__input">
									{{obj.details}}
								</p>
							</div>
							<div class="log__group log__group_textarea">
								<label>Выполняет:</label>
								<p class="log__input">
									{%if obj.worker.first_name == NULL%}Ожидается{%else%}{{obj.worker.first_name}} {{obj.worker.last_name}}{%endif%}
								</p>
							</div>
						</div>
						<div class="log__btn">
							{%if obj.worker.first_name == NULL%}<input id="agree" type="submit" data-submit value="Принять" class="btn btn_agree"/>{%endif%}
							<!--<input id="reject" type="submit" data-submit value="Отклонить" class="btn btn_reject"/>-->
						</div>
					</form>
				</div>
			</div>
			<div class="row">
				<div class="col-lg">
					<div class="chat-window">
						{%for chat_message,who_sent in chat%}
						<div class="user_{%if who_sent == 0%}self{%endif%}{%if who_sent == 1%}different{%endif%}">{{chat_message}}</div>
						<br>
						{%endfor%}
					</div>
					<form action="{%url 'helpdesk:send_ticket_message'%}" method="POST" class="form-chat d-flex">
						{% csrf_token %}
						<textarea name="chat-message" placeholder="Введите текст" required></textarea>
						<input type="hidden" name="ticket_num" value="{{obj.pk}}">
						<input type="hidden" name="user_type" value="user">
						<button type="submit" class="chat-send"></button>
					</form>
				</div>
			</div>
		</div>
	</section>	
{%endblock%}